h

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,24 +1,40 @@
 #!/usr/bin/env bash
 #handling background processs
-if [ "${1}" == "start" ]
-then
+#!/bin/bash
+
+if [ "$1" == "start" ]; then
+    if [ -f "/var/run/my_process.pid" ]; then
+        echo "Error: Process is already running."
+        exit 1
+    fi
+
     ./manage_my_process &
-    touch /var/run/my_process.pid
-    echo "$!" > /var/run/my_process.pid
+    echo $! > /var/run/my_process.pid
     echo "manage_my_process started"
-elif [ "${1}" == "stop" ]
-then
+elif [ "$1" == "stop" ]; then
+    if [ ! -f "/var/run/my_process.pid" ]; then
+        echo "Error: Process is not running."
+        exit 1
+    fi
+
+    PID=$(cat /var/run/my_process.pid)
+    kill $PID
+    rm /var/run/my_process.pid
     echo "manage_my_process stopped"
-    kill "$(cat /var/run/my_process.pid)"
+elif [ "$1" == "restart" ]; then
+    if [ ! -f "/var/run/my_process.pid" ]; then
+        echo "Error: Process is not running."
+        exit 1
+    fi
+
+    PID=$(cat /var/run/my_process.pid)
+    kill $PID
     rm /var/run/my_process.pid
-elif [ "${1}" == "restart" ]
-then
-    kill "$(cat /var/run/my_process.pid)"
-    rm /var/run/my_process.pid
+
     ./manage_my_process &
-    touch /var/run/my_process.pid
-    echo "$!" > /var/run/my_process.pid
+    echo $! > /var/run/my_process.pid
     echo "manage_my_process restarted"
 else
-    echo "Usage: manage_my_process {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 fi
